[phases.setup]
nixPkgs = ['python311', 'ffmpeg']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'python -m uvicorn scripts.yt_metadata_api:app --host 0.0.0.0 --port $PORT'